# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: 'https://hemara.nz/#about'
    weight: 1
  - name: Publications
    url: 'https://hemara.nz/#papers'
    weight: 2
  - name: Experience
    url: 'https://hemara.nz/experience/'
    weight: 3
#  - name: Academic
#    parent: tags
#    url: tags/academic/
#    weight: 10